### ISSUE TITLE
不能同时打开多个terminal tab (vim 8.1) 

### ISSUE THREAD

**Issue by busydoggo** [PangPangPangPangPang/vim-terminal#1]
:buffers
  1 #a + ".vimrc"                       line 186
  6 %aR  "!/usr/bin/zsh [wyz@ubuntu18: ~]" line 1
Press ENTER or type command to continue

:VSTerminalOpenNew
Error detected while processing function VSTerminalOpenNew[3]..VSTerminalCreateNew:
line    7:
E948: Job still running (add ! to end the job)
Press ENTER or type command to continue

没有成功打开过tab, 多次按F10会出现terminal镜像buffer

**Comment by jacklanda** [comment]
> :buffers
> 1 #a + ".vimrc" line 186
> 6 %aR "!/usr/bin/zsh [wyz@ubuntu18: ~]" line 1
> Press ENTER or type command to continue
> 
> :VSTerminalOpenNew
> Error detected while processing function VSTerminalOpenNew[3]..VSTerminalCreateNew:
> line 7:
> E948: Job still running (add ! to end the job)
> Press ENTER or type command to continue
> 
> 没有成功打开过tab, 多次按F10会出现terminal镜像buffer

the same error arise on me too

**Comment by PangPangPangPangPang** [comment]
推荐用大佬的实现 https://github.com/skywind3000/vim-terminal-help
